### PR TITLE
Update kibana index

### PR DESCRIPTION
**Pull request by dbason**
@tybalex  @kralicky 
I've prettified the json to allow for easier maintenance.

I've also change the index we post the kibana objects to.  The `.kibana_92668751_admin_1` index is the index for the admin user space, we should just use the generic space `.kibana_`

### CODE REVIEW

**Comment by tybalex** [comment]
@dbason cool. have you tested this with opendistro-es in Opni? the reason I did post to `.kibana_92668751_admin_1` is I found that posting to `.kibana_1` didn't work..

**Comment by dbason** [comment]
I've tested posting directly to opendistro with curl, and confirming the index pattern is created, but not via the opni init container.

I'll create a new cluster and test deploying the quickstart with this change.  My suspicion is that there might be a race condition with kibana starting up and creating the indices, so I suspect moving to a job that runs after opendistro-es is configured might solve that.

**Comment by tybalex** [comment]
> I've tested posting directly to opendistro with curl, and confirming the index pattern is created, but not via the opni init container.
> 
> I'll create a new cluster and test deploying the quickstart with this change. My suspicion is that there might be a race condition with kibana starting up and creating the indices, so I suspect moving to a job that runs after opendistro-es is configured might solve that.

That makes sense. Pls go ahead moving it to a job.
 Can you also verify if the kibana dashboard got created by running ur updated code? Because it is the main goal of this thread.

**Comment by tybalex** [comment]
hey Dan, did you get a chance to move it to a job?

**Comment by dbason** [comment]
@kralicky was looking at that.  I think we will probably just fold it into the operator.

**Comment by dbason** [comment]
@tybalex I've tested this now with the new code in the operator, and after moving everything to the global tenant it works.

**Comment by tybalex** [comment]
> @tybalex I've tested this now with the new code in the operator, and after moving everything to the global tenant it works.

sounds great! let's merge it with the operator then.

**Review by kralicky — APPROVED** [review]

**Pull request merged**
